name: vre_new
description: "A custom VRE Train Riding App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^6.1.3
  intl: ^0.19.0
  volume_controller: ^2.0.0
  battery_plus: ^6.0.0
  geolocator: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
